name: Generate Java API Client

on:
    push:
    workflow_dispatch:
jobs:
  generate-client:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Java JDK
        uses: actions/setup-java@v4.7.1
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'
          overwrite-settings: false
      - run: 'mvn package'
      - run: 'mvn deploy'
        if: github.ref_name == 'main'
