name: Generate Java API Client

permissions:
    packages: read
on:
    push:
    workflow_dispatch:
jobs:
  generate-client:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Java JDK
        uses: actions/setup-java@v4.7.1
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'
          overwrite-settings: false
          settings-path: ${{ github.workspace }}/.m2
      - run: 'cat ${{ github.workspace }}/.m2/settings.xml'
        env:
          GITHUB_ACTOR: "token"
          GITHUB_TOKEN: "dummy"
      - run: 'mvn package'
        env:
          GITHUB_ACTOR: "token"
          GITHUB_TOKEN: ${{ secret.ORG_ACCESS_TOKEN }}
      - run: 'mvn deploy:deploy'
        if: github.ref_name == 'main'
        env:
          GITHUB_ACTOR: "token"
          GITHUB_TOKEN: ${{ github.token }}
